name: "project-name"
layout:
  project-root:
    - CODE-OF-CONDUCT.md
    - development:
        - bugs:
            - TEMPLATE-BUG.md
            - bugs.md
        - house-keeping:
            - TEMPLATE-HOUSE-KEEPING.md
            - house-keeping.md
        - meta-tags:
            - TEMPLATE-META-TAG.md
            - meta-tags.md
    - domains:
        - TEMPLATE-DOMAIN.md
        - domains.md
    - requirements:
        - TEMPLATE-REQUIREMENT.md
        - requirements.md
    - features:
        - TEMPLATE-FEATURE.md
        - features.md
    - rules:
        - Rules-of-Rules.md
        - rules.md
        - TEMPLATE-RULE.md
        - business:
            - business-rules.md
            - rule-001.md
        - ui:
            - ui-rules.md
            - rule-001.md
    - work-items:
        - epics:
            - TEMPLATE-EPIC.md
            - epics.md
        - stories:
            - TEMPLATE-STORY.md
            - stories.md
        - tasks:
            - TEMPLATE-TASK.md
            - tasks.md
        - spikes:
            - TEMPLATE-SPIKE.md
            - spikes.md
        - sprints:
            - TEMPLATE-SPRINT.md
            - sprints.md
        - rules-of-work-items.md
    - README.md
    - version.txt
